### ISSUE TITLE
[FR] `readOpenMemory` variant with pointer and size to work with mmap

### ISSUE THREAD

**Issue by FooIbar** [zhanghai/libarchive-android#2]

**Comment by zhanghai** [comment]
It seems to me you can implement it normally with the `archive_read_open` call - see also https://github.com/bramp/libarchive/blob/master/libarchive/archive_read_open_memory.c .

**Comment by FooIbar** [comment]
> It seems to me you can implement it normally with the `archive_read_open` call - see also https://github.com/bramp/libarchive/blob/master/libarchive/archive_read_open_memory.c .

`ReadCallback` requires a ByteBuffer as well.
https://github.com/zhanghai/libarchive-android/blob/1d91b0abb28e14370d8dc3c29770161f5d9bb34d/library/src/main/java/me/zhanghai/android/libarchive/Archive.java#L266
BTW is the `?` a typo?

**Comment by zhanghai** [comment]
> ReadCallback requires a ByteBuffer as well.

What about [`MappedByteBuffer`](https://docs.oracle.com/javase/8/docs/api/java/nio/MappedByteBuffer.html)?

> BTW is the ? a typo?

Ah yes, I think it's a typo.

**Comment by FooIbar** [comment]
> > ReadCallback requires a ByteBuffer as well.
> 
> What about [`MappedByteBuffer`](https://docs.oracle.com/javase/8/docs/api/java/nio/MappedByteBuffer.html)?

`FileChannel.map` has some annoying limitations, like, the size must not exceed `Integer.MAX_VALUE` (i.e. 2 GB).

**Comment by zhanghai** [comment]
I can add an `Archive.readOpenMemoryUnsafe()` that takes a raw pointer and size. Out of curiosity, why do you need to `mmap()` the file instead of using regular IO (or `pread()`)?

Meanwhile I tried but couldn't easily add an `Archive.writeOpenMemoryUnsafe()` because it's a bit awkward for how to return the actually used memory size in an async way without the `ByteBuffer`. So I hope you aren't doing `mmap()` for writes :P

---

Note to myself: https://bugs.openjdk.org/browse/JDK-6347833 - We could have used `MemorySegment` if and when our minimum SDK version supported Java FFM API (JEP 454).

**Comment by zhanghai** [comment]
Actually I think I can add the `Archive.writeOpenMemoryUnsafe()` because I can & should add a Java API for getting the `used` out-parameter any time.

**Comment by FooIbar** [comment]
Thanks!
I need to read multiple entries from the archive simultaneously.
`pread()` does work to some extent, but `mmap()` woud be better.

**Comment by zhanghai** [comment]
> I need to read multiple entries from the archive simultaneously.

Out of curiousity, how did you manage to do that? I thought `libarchive` isn't thread safe by itself:

> The library is not thread aware, however. It does no locking or thread management of any kind. If you create a libarchive object and need to access it from multiple threads, you will need to provide your own locking.

https://github.com/libarchive/libarchive/blob/master/README.md

(Closing because the new APIs have been released in v1.1.0 - but please feel free to keep commenting.)

**Comment by FooIbar** [comment]
I read through the archive to get the entry list first, then use individual archive objects for requested entries.

**Comment by zhanghai** [comment]
> then use individual archive objects for requested entries.

1. Does that mean you are creating multiple `archive` objects with `archive_read_open_memory` in order to read in parallel?
2. How are you reusing the entries read earlier in order to read its data? I can imagine one can keep calling `archive_read_next_header` until the entry name matches with the desired entry, and do this in parallel. But maybe you know some better way to skip directly to the desired entry?

**Comment by FooIbar** [comment]
1\) Yes 2) That's what I did

Here is the commit https://github.com/FooIbar/tachiyomi/commit/35f5f0d8ddbfab7419e7907cf38944f55aa3efad

**Comment by zhanghai** [comment]
I see. I was looking at [the other apps of yours](https://github.com/FooIbar/EhViewer/blob/main/app/src/main/cpp/archive.c) which is using `mmap()` and `madvise()` with its own build of libarchive.

And curious, will you be upstreaming https://github.com/FooIbar/tachiyomi/commit/35f5f0d8ddbfab7419e7907cf38944f55aa3efad to Mihon? (If that's the case I'll be happy that my code is part of Mihon as well - which I'm using right now.)

**Comment by FooIbar** [comment]
See https://github.com/mihonapp/mihon/pull/949

**Comment by zhanghai** [comment]
Nice! Subscribed to that PR.

**Comment by AntsyLich** [comment]
> If that's the case I'll be happy that my code is part of Mihon as well - which I'm using right now.

I use your file manager too 🙃

**Comment by zhanghai** [comment]
> I use your file manager too 🙃

Glad you like it 🤠
